<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>
    <Authors>Anomek</Authors>
    <Version>0.4.4.0</Version>
    <Description>Simulate ultimate raid mechanics solo client-side</Description>
    <RootNamespace>AnoMech</RootNamespace>
    <PackageProjectUrl>https://github.com/anomek/AnoMech</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AnoMech.Relay/AnoMech.Relay.csproj" />
    <InternalsVisibleTo Include="AnoMech.Tests" />
    <AdditionalFiles Include="BannedSymbols.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NAudio.Core" Version="2.2.1" />
    <PackageReference Include="NAudio.WinMM" Version="2.2.1" />
    <PackageReference Include="NVorbis" Version="0.10.5" />
  </ItemGroup>
</Project>
